services:
  - type: web
    name: blitzapp
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz prisma migrate deploy --preview-feature && blitz build
    startCommand: blitz start
    envVars:
      # ⚠️  You must set SESSION_SECRET_KEY env var through the UI.
      # Add this env name, then a "generate" button will appear in the value box
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blitzapp-db
          property: connectionString

databases:
  - name: blitzapp-db
    plan: starter
