name: CI

on:
  pull_request:
    branches: [master, canary]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Compressed Size
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Count size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          exclude: "{./nextjs/**}"
